theme: jekyll-theme-cayman
title: The 3D Slicer Open Source Platform for Medical Image Computing, Image-guided Therapy and Robotics Research
description: Workshop CBEB & CLAIB 2022, Monday, October 24 2022
